### ISSUE TITLE
Maybe you could add an instruction about how to set the inapp purchase setting to true

### ISSUE THREAD

**Issue by evermeer** [younatics/MotionBook-Source#1]
If you want to run the app from source code then it would be nice if you could also go to the examples. For this you need to set the inapp puchase to true like this:

`        Settings().setInappPurchased(value: true)`

**Comment by younatics** [comment]
Great Idea! However, This source code will be the distribution version, so it will be hard to apply. But you can see examples by adding only one line that you mentioned. Thanks!

**Comment by evermeer** [comment]
or you could put it in a:

```
#if DEBUG
Settings().setInappPurchased(value: true)
#endif
```
